### ISSUE TITLE
more opts

### ISSUE THREAD

**Issue by jcoignet** [jcoignet/nmap#4]
## TODO:
- [x] --timeout %d . set it to opts->timeout. Min 1
- [x] scan window WIN
- [ ] if scan UDP selected don't allow threading

**Comment by jcoignet** [comment]
updated
